# Generated by Django 4.2.7 on 2023-11-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTercerEntregable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('almacenamiento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('almacenamiento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('almacenamiento', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
